### ISSUE TITLE
Migrating RTC 6.0.1 to GHE history of changes not complete

### ISSUE THREAD

**Issue by tokra** [WtfJoke/rtc2git#113]
We migrated our JAZZ SCM version 6.0.1 but looking at the some files changes history is not complete comparing to JAZZ history.

We have Github Enterprise repository which is not reachable outside IBM.

Attaching migration log.

[migration.txt](https://github.com/rtcTo/rtc2git/files/603232/migration.txt)

**Comment by tokra** [comment]
here is comparison of GHE & JAZZ history of same file:
**GHE:**
![image](https://cloud.githubusercontent.com/assets/2188084/20478546/db74b01e-afda-11e6-9ba7-d638e4a7aa1d.png)
**JAZZ:**
![image](https://cloud.githubusercontent.com/assets/2188084/20478540/d5455428-afda-11e6-88e9-9dae0ceca3fe.png)

As you can see its clearly messed up :-(

**Comment by to-kra** [comment]
I also provided history files, but seems that it does n

**Comment by tokra** [comment]
I also used history files and enabled in config.ini but i got this:
`16:20:16 - Set new Flowtargets
Problem running 'set flowtarget':
The specified value for the --current option is not valid. Try 'lscm help set flowtarget' for more information.
16:20:18 - Warning - UseProvidedHistory is set to false, merge-conflicts are more likely to happen.
 For more information see https://github.com/rtcTo/rtc2git/wiki/Getting-your-History-Files`

**Comment by tokra** [comment]
![image](https://cloud.githubusercontent.com/assets/2188084/20489326/769dc83a-b00a-11e6-9820-a3cb7e6612c5.png)

And repo is almost empty... so nothing migrated

**Comment by WtfJoke** [comment]
According to the log and your second comment, there is something wrong with setting your flowtarget, which is most likely the reason, why your history is messed up.

What happens if you execute the following command (with replacing REPO/WORKSPACENAME/STREAMUUID)?
`lscm set flowtarget -r REPO WORKSPACENAME --default --current STREAMUUID`

And can you execute also the help and tell me whats the result:
`lcm help set flowtarget `


EDIT: I saw your screenshot in #105 
The console says its not a valid streamuuid. 
Is your streammuuid really the number 1410? Or is this rather the name of the stream?
