### ISSUE TITLE
Migrating multiple streams?

### ISSUE THREAD

**Issue by timothymcmackin** [WtfJoke/rtc2git#117]
Hello. Thanks for the great tool!

@WtfJoke's [answer on this Stack Overflow question](http://stackoverflow.com/questions/23928927/how-to-migrate-from-rtc-jazz-to-git) implies that rtc2git can migrate multiple RTC streams to one Git repo, creating one branch per stream. 

How do I specify multiple streams for rtc2git to migrate? I've tried putting multiple stream UUIDs in `StreamToMigrate`, both comma and space-separated, but I get a message that the list of stream IDs is not a valid git branch name.

Should I import each stream with a separate config.ini file and separate run of migrate.py?

**Comment by WtfJoke** [comment]
Hi Tim

As you figured out, putting Multiple streams in StreamToMigrate doesnt work.

I just created a [wiki page](https://github.com/rtcTo/rtc2git/wiki/Migrating-multiple-streams-into-one-git-repo), because another user asked the same question in #114 and I wasnt aware that I didnt describte how to achieve that.


You can do the following in order to migrate multiple streams:
Copied from wiki:
1. Finish Migration of 1 Stream.
2. Backup the current git repo (in case migration of next stream fails)
3. Change StreamToMigrate to the next stream, change WorkspaceName to a different one
4. Rerun the script --> It should find the existing git repo and continue.

**Comment by timothymcmackin** [comment]
Seems to work fine. I might have figured that out from the notes in the config.ini examples, but your explanation made it much easier. Thanks!
