### ISSUE TITLE
Fails to deal with multiple changesets that build on top of each other

### ISSUE THREAD

**Issue by JCDClark** [WtfJoke/rtc2git#119]
Hi.

We're currently looking to migrate our large RTC repo to git. I initially ran the tool for our mainline stream and after 2-3 days, the migration completed (~17k changesets). After uploading the resulting git repo to github, the migration looked successful - history was there and I could run the product after checking it out and doing a local build in Eclipse.

I then needed to figure out how to get our maintenance streams into the same repo. The approach I am currently following is to reset the head of the master branch to just before the stream was branched, configure the RTC workspace used for migration to be at the earliest baseline in the support stream and then resume the tool. Once completed, push the state of master into a new branch and then repeat until all branches are done. After a couple of tweaks, this appeared to be working great.

I came across an issue whilst doing this for one of our streams however and this led me to discover that our initial migration had failed in at least two places. The history for a file contained only one commit that was nothing to do with that file and the change that should have been made in that commit had not been made. This had happened in such a way it didn't affect the product but would affect a proper release build. Obviously this means that I cannot trust the migration, even if it was 99% fine.

By investigating this problem, it seems likely it is caused by accepting a change that was delivered alongside multiple changesets that built on that (completed) changeset. I see that there used to be functionality to try to address this (rtcFunctions.py:retryacceptincludingnextchangesets) but this was commented out in favour of a new approach. I'm going to play around with reintroducing this method and see whether I can have more success.

Can you offer any advice in getting around this problem?

Thanks,
James

**Comment by WtfJoke** [comment]
Hi James

> By investigating this problem, it seems likely it is caused by accepting a change that was delivered alongside multiple changesets that built on that (completed) changeset.

When I tested it, using my previous company big repo. I had some simmilar issues. Most of it were gone, by introducing this method. As you already analyzed, later on there was another approach (by modifying the accept command), which was suggested by a teammember. Im not sure if I retested the code with the big repo, though. 

You can try reintroducing the method. The Problem is more or less, that there can be sometimes huge gaps, between the changeset, which needs to accepted together. In my personal opinion its a flaw of rtc that you can not accept one changeset after another, so you end up having something accepted which doesnt do any change.

Neverthless, as another advice, you can try set up [rtc2gitcli](https://github.com/rtcTo/rtc2gitcli). There we worked with the java sdk and I was told that we experienced less problems with our big repos. We actually migrated our huge repos with that tool.

I hope you suceed with one of these 2 approaches.

**Comment by JCDClark** [comment]
Ah, thank you! The rtc2gitcli project looks interesting. I think I will give that a go.

I realised that my approach to try and fix the issue using rtc2git likely won't actually do anything different - at the end of the day, it will still accept changesets one by one. It could potentially use `lscm status` to check for conflicts, work out the minimal set of changes necessary to resolve conflicts, unload the change sets and then accept them as one again but I'm not too hopeful with that. I'm still actually not sure what the problem is - just by experimenting with a dummy workspace within RTC, by accepting the change sets one by one, any conflicts eventually get resolved and everything looks fine. For some reason, the changes aren't committed into the git repo though and I can't see why. Will continue to play with it!

Thanks for the suggestions,
James
