### ISSUE TITLE
No repositories found based on path

### ISSUE THREAD

**Issue by ljhaywar** [WtfJoke/rtc2git#14]
The script is executing! Yay!  Unfortunately, I'm seeing some errors with the lcsm commands, and the changes aren't being put in my git repo:
![error](https://cloud.githubusercontent.com/assets/3940962/7517191/9c6084ac-f4a1-11e4-97a7-484b19497c6d.png)

I've tried running with and without useProvidedHistory, and I get the same errors either way. I've also tried running with the stream's name instead of UUID. Any ideas on how to fix?

**Comment by WtfJoke** [comment]
Hmm it looks like the executed lscm command cant find your rtc repo uri/workspace. Can you verifiy if its correct by using lscm login -r in any console?

**Comment by ljhaywar** [comment]
I am able to successfully login using
lscm login -r https://hub.jazz.net/ccm11 -u myusername -P mypassword.

The server is Jazz Team Server 5.0.2.

**Comment by WtfJoke** [comment]
ok thats good. Strange error you get there.... Do you get the same error when you try to run the lscm accept command in the folder where your workspace is loaded?

**Comment by ljhaywar** [comment]
My Eclispe workspace has all of the changes loaded, so when I run the accept command I'm getting:
Accepting changes:
Workspace unchanged.

I just did some searching, and the script is creating my repository workspace successfully, but there are no files in it.

**Comment by WtfJoke** [comment]
So according to your description your workspace gets updated, but not the one in the folder.

You could try two things. Start on a not existing workspace.
1. After the first accept of "Sharing project". Can you make a reload of the workspace? (eg. lscm load -r https://hub.jazz.net/ccm11) 
2. Specify a target on your accept by adding parameter --target to the accept commands. (eg. lscm accept -v --overwrite-uncommited --target "MYWORKSPACENAME" --changes CHANGES)

One of those should make a change...

**Comment by ljhaywar** [comment]
1.  Are you saying to do this while the script is loading?
2.  Are you suggesting to modify the script code to have an extra param?
3.  I did a little more testing.  I've been using a new repo workspace for each script run.  In the command line, I ran 
lcsm accept -v --overwite-uncommitted --changes _mylonguuid --target "myGitTestWorkspace13" -r https://hub.jazz.net/ccm11 -u myusername -P mypassword
The command ran successfully, and when I view the repo workspace files in Eclipse, I can see the changeset in it.

Perhaps I need to modify my version of the script to use --target?

**Comment by WtfJoke** [comment]
1. Either making a break in the script or doing the steps manually.
2. Yes (should be only one change here on this line: https://github.com/WtfJoke/rtc2git/blob/develop/rtcFunctions.py#L93)
3. Did I get this right. In the folder where your workspace gets loaded there are now changes? Therefore "git status" shows something?

So it really looks like it makes a different in your case. I need to test with my use case.... In my case it wasnt necessary to specify a target.

**Comment by ljhaywar** [comment]
Thank you so much for your help!  I was able to get the script running by making modifications to the Accept command.  My changes are in https://github.com/ljhaywar/rtc2git/pull/1/commits.  The script is successfully running and saving RTC history to a git repo.

Can you explain how it handles multiple streams?  Does each stream translate to a new branch in the same git repository?

**Comment by WtfJoke** [comment]
Good to hear that it works now. :smile: . I was having a look at your change. Looks good. :+1:  Nevertheless I think -r is not required and it should work without it as well (since we login at the beginning of the script).

About multiple streams:
Each stream creates a git branch named after the stream.
The idea is that you run a migration for each stream. 

In detail how the script works is like that (just the branching stuff of course):
1. Creates empty git repo (default branch is master)
2. RTC Workspace (created) and loaded
3. Create new git branch (named after rtc stream)
4. Do all the update in rtc workspace and do the same in git

At the end of the migration you have a master branch (with the initial rtc workspace, which you could throw away) and another branch named after your rtc stream. The idea is that you can merge or rebase it afterwards on your own to your master branch.

I just figured out that I missed something to implement. My Idea was that you can run multiple migration on the same git-repo. Since the branches don't conflict (unless two different streams have the same name, but lets assume this isn't possible) it is possible without any problems
So on the same git-repo you could run multiple migrations,

**Comment by ljhaywar** [comment]
Thanks for the info!  Your script is going to save us a ton of time!
