### ISSUE TITLE
Migrate based on change sets

### ISSUE THREAD

**Issue by jacobilsoe** [WtfJoke/rtc2git#25]
Instead of migrating using baseline comparison I was wondering if it might be easier to just use change sets. So the migration process would be something like:

1. Create a repository workspace
2. Discard all change sets
3. Accept one change set at a time and commit to git for each one

Would this not work?

**Comment by jacobilsoe** [comment]
Discarding all change sets manually and just starting the migration seems to work just fine.

**Comment by WtfJoke** [comment]
Yeah I think this works as well. However I honestly never thought about it this way...

But what im not sure is, what exactly is the advantage in this case? You still need to keep an order or not? Or is it just because you dont need to set a baseline?

Somebody else, did something similar (https://github.com/WtfJoke/rtc2git/issues/19#issuecomment-103627056), she did it with suspend, cause somehow some changeset didnt appear, when they were discarded.

Did you need to adjust the script at all, or kept it like this?

**Comment by jacobilsoe** [comment]
My problem is that I do not have baselines for the initial change sets. So I just tried discarding all change sets from the repository workspace and then useExistingWorkspace = True in the config file. In this case I can use the script as it is (almost, I had to add a -r repo to the accept command). Now and then I still get merge conflicts when accepting change sets though. What's the best way of handling these?

**Comment by WtfJoke** [comment]
> Now and then I still get merge conflicts when accepting change sets though. What's the best way of handling these?

Did you use "useProvidedHistory" as well (see https://github.com/WtfJoke/rtc2git/wiki/Getting-your-History-Files)? Else I would suggest you doing that. In my case it reduced the amount of merges. However in some cases you can still get some merge conflicts from time to time. In this case the best way to solve them is load the workspace in eclipse and resolve it there. Usually you can just accept some changesets together to avoid a conflict (because somebody usually solved a merged conflict by delivering a merge-changeset). 

After you did that you can reload the workspace in the folder where the migration takes place and do the appropriate git command and then continue as usual (for example starting the script again with resume in case you have aborted it before)

**Comment by jacobilsoe** [comment]
Yes, I do use history. I was kind of hoping I could prevent merge conflicts so that the migration would not need any manual intervention but unfortunately it does not seem to be the case.

**Comment by WtfJoke** [comment]
> Yes, I do use history. I was kind of hoping I could prevent merge conflicts so that the migration would not need any manual intervention but unfortunately it does not seem to be the case.

Yes, sadly I didnt found a solution for that problem. I would like to achieve this as well.... :persevere:
